version: '3.7'

services:
  redis: 
    image: redis:latest
    env_file:
      - core/config_data/.env
    restart: on-failure
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    env_file:
      - core/config_data/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - 5432:5432
  bot:
    build: .
    command: sh -c 'python -m bot'
    env_file:
      - core/config_data/.env
    restart: always
    depends_on:
      - redis
      - db
volumes:
  pgdata: